name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Install Node 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: apt-get update
      run: sudo apt-get -y update

    - name: Install mesa and xvfb
      run: sudo apt-get -y install mesa-utils xvfb libgl1-mesa-dri libglapi-mesa libosmesa6 xserver-xorg-dev libxi-dev libxext-dev

    - name: Install NPM Packages
      run: npm install

    - name: Bootstrap NPM Packages
      run: npm run bootstrap

    - name: Lint
      run: npm run lint

    - name: Compile
      run: npm run build

    - name: Execute Jest unit tests for Node support
      run: npm run test:node:xvfb

    - name: Execute Karma unit tests for browser support
      run: npm run test:browser

    - name: Publish Code Coverage
      uses: codecov/codecov-action@v1
      with:
        file: build/cobertura-coverage.xml

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: fim-${{github.run_number}}
        path: |
          **
          !**/node_modules/**
