name: Release

on:
  repository_dispatch:
    inputs:
      build:
        description: 'Build number'
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: fim-${{github.event.inputs.build}}.zip
